-- AlterTable
ALTER TABLE "Invite"
  ADD COLUMN "revokedAt" TIMESTAMPTZ(6),
  ADD COLUMN "lastSentAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "sendCount" INTEGER NOT NULL DEFAULT 1;
